services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - .:/frontend
    ports:
      - "4200:4200"
    user: 
        1000:1000