# Generated by Django 5.1.1 on 2024-09-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telethon_app', '0003_telegramaccount_subscribed_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='telegram_id',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
