# Generated by Django 5.1.1 on 2024-09-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telethon_app', '0004_telegramaccount_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccount',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
